# Generated by Django 5.2.6 on 2025-09-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedphone',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
